---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: Bekannte Einschränkungen kennzeichnen Plattformen, Geräte oder Funktionen, die von dieser Produktversion nicht unterstützt werden oder nicht ordnungsgemäß mit ihr zusammenarbeiten. Überprüfen Sie diese Einschränkungen sorgfältig. 
---
= Bekannte Einschränkungen für Cloud Volumes ONTAP bei allen Cloud-Anbietern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen kennzeichnen Plattformen, Geräte oder Funktionen, die von dieser Produktversion nicht unterstützt werden oder nicht ordnungsgemäß mit ihr zusammenarbeiten. Überprüfen Sie diese Einschränkungen sorgfältig.

Die folgenden Einschränkungen gelten für Cloud Volumes ONTAP bei allen Cloud-Anbietern: AWS, Azure und Google Cloud.



== Nicht unterstützte ONTAP-Funktionen

Die folgenden Funktionen werden von Cloud Volumes ONTAP nicht unterstützt:

* Inline-Deduplizierung auf Aggregatebene
* Hintergrunddeduplizierung auf Aggregatebene
* Festplattenwartungszentrum
* Datenträgerbereinigung
* FabricPool-Spiegelung
* Fibre Channel (FC)
* Flash Pools
* Unendliche Volumes
* Schnittstellengruppen
* Intranode LIF-Failover
* MetroCluster
* Multi-Admin-Verifizierung
+
Die Aktivierung der Multi-Admin-Verifizierung auf Cloud Volumes ONTAP führt zu einer nicht unterstützten Konfiguration.

* RAID4, RAID-DP, RAID-TEC (RAID0 wird unterstützt)
* Service Processor
* SnapLock Compliance- und Enterprise-Modus (nur Cloud WORM wird unterstützt)
* SnapMirror Synchronous
* VLANs
* SMB Continuous Availability (CA)
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Ständig verfügbare SMB-Shares"^] für unterbrechungsfreie Vorgänge werden nicht unterstützt.





== Maximale Anzahl gleichzeitiger Replikationsvorgänge

Die maximale Anzahl gleichzeitiger SnapMirror oder SnapVault Übertragungen für Cloud Volumes ONTAP beträgt 100 pro Knoten, unabhängig vom Instanztyp oder Maschinentyp.



== Snapshots von Cloud-Anbietern dürfen nicht für Ihre Backup und Recovery-Pläne verwendet werden

Sie sollten die Snapshots Ihres Cloud-Anbieters nicht als Teil Ihres Backup und Recovery-Plans für Cloud Volumes ONTAP-Daten verwenden. Sie sollten immer ONTAP Snapshot-Kopien oder Backup-Lösungen von Drittanbietern verwenden, um Daten, die auf Cloud Volumes ONTAP gehostet werden, zu sichern und wiederherzustellen.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["Erfahren Sie, wie Sie NetApp Backup und Recovery verwenden, um ONTAP Daten zu sichern und wiederherzustellen"^].


NOTE: ONTAP-Konsistenzpunkte im WAFL-Dateisystem bestimmen die Datenkonsistenz. Nur ONTAP kann das WAFL-Dateisystem anhalten, um einen absturzkonsistenten Backup zu erstellen.



== Cloud Volumes ONTAP unterstützt nur reservierte und bedarfsgesteuerte VM-Instanzen

Cloud Volumes ONTAP kann entweder auf einer reservierten oder einer On-demand VM-Instanz von Ihrem Cloud-Anbieter ausgeführt werden. Andere Arten von VM-Instanzen werden nicht unterstützt.



== Automatische Lösungen für das Ressourcenmanagement von Anwendungen sollten nicht verwendet werden

Automatische Lösungen für das Ressourcenmanagement von Anwendungen sollten Cloud Volumes ONTAP-Systeme nicht verwalten. Dies kann zu einer Änderung auf eine nicht unterstützte Konfiguration führen. Beispielsweise könnte die Lösung Cloud Volumes ONTAP auf einen nicht unterstützten VM-Instanztyp ändern.



== Software-Updates müssen über die NetApp Console abgeschlossen werden

Aktualisierungen von Cloud Volumes ONTAP müssen über die NetApp Console durchgeführt werden. Sie sollten Cloud Volumes ONTAP nicht mit dem System Manager oder der CLI aktualisieren. Dies kann die Systemstabilität beeinträchtigen.



== Cloud Volumes ONTAP-Bereitstellung darf nicht über die Konsole Ihres Cloud-Anbieters geändert werden

Änderungen an einer Cloud Volumes ONTAP-Konfiguration über die Konsole Ihres Cloud-Anbieters führen zu einer nicht unterstützten Konfiguration. Jegliche Änderungen an den von der Console erstellten und verwalteten Cloud Volumes ONTAP-Ressourcen können die Systemstabilität und die Fähigkeit der Console, das System zu verwalten, beeinträchtigen.


NOTE: Nach der ersten Bereitstellung wird die Änderung des für Cloud Volumes ONTAP-Ressourcen verwendeten Azure-Abonnementnamens unterstützt.



== Datenträger und Aggregate müssen über die Console verwaltet werden

Alle Datenträger und Aggregate müssen direkt von der Konsole aus erstellt und gelöscht werden. Sie sollten diese Aktionen nicht von einem anderen Verwaltungstool aus durchführen. Andernfalls kann dies die Systemstabilität beeinträchtigen, die Möglichkeit, in Zukunft Datenträger hinzuzufügen, erschweren und möglicherweise redundante Gebühren des Cloud-Anbieters verursachen.



== SnapManager Lizenzierungsbeschränkung

SnapManager-Lizenzen pro Server werden mit Cloud Volumes ONTAP unterstützt. Lizenzen pro Speichersystem (SnapManager-Suite) werden nicht unterstützt.



== Einschränkungen mit Drittanbieter-Agenten und Erweiterungen

Agenten von Drittanbietern und VM-Erweiterungen werden auf Cloud Volumes ONTAP VM-Instanzen nicht unterstützt.
