---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Mehrere Cloud Volumes ONTAP-Konfigurationen werden in Google Cloud unterstützt. 
---
= Unterstützte Konfigurationen für Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mehrere Cloud Volumes ONTAP-Konfigurationen werden in Google Cloud unterstützt.



== Unterstützte Konfigurationen gemäß Lizenz

Cloud Volumes ONTAP ist in Google Cloud als Einzelknotensystem und als hochverfügbares (HA) Knotenpaar für Fehlertoleranz und unterbrechungsfreie Vorgänge verfügbar.

Die Aufrüstung eines Einzelknotensystems auf ein HA-Paar wird nicht unterstützt. Wenn Sie zwischen einem Einzelknotensystem und einem HA-Paar wechseln möchten, müssen Sie ein neues System bereitstellen und Daten vom bestehenden System auf das neue System replizieren.

Cloud Volumes ONTAP kann entweder auf einer reservierten oder einer On-Demand VM-Instanz Ihres Cloud-Anbieters ausgeführt werden. Lösungen, die andere VM-Instanztypen verwenden, werden nicht unterstützt.

[role="tabbed-block"]
====
.Kapazitätsbasierte Lizenzen
--
[cols="h,d,d,d"]
|===
|  | Freemium | Optimiert ^4^ | Kapazitätsbasierte Lizenz (Essentials und Professional) 


| Maximale Systemkapazität (Festplatten + Objektspeicher) | 500 GiB  a| 
Mit kapazitätsbasierter Lizenzierung unterstützt jedes Cloud Volumes ONTAP-System das Tiering zu Objektspeicher. Die gesamte getierete Kapazität kann bis zum Bucket-Limit des Cloud-Anbieters skaliert werden. Obwohl die Lizenz keine Kapazitätsbeschränkungen vorsieht, sollten Sie die  https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool Best Practices"^] befolgen, um optimale Leistung, Zuverlässigkeit und Kosteneffizienz bei der Konfiguration und Verwaltung des Tierings zu gewährleisten.



| Unterstützte Maschinentypen ^1^  a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n2-standard-4
* n2-standard-8

 a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| Unterstützte Datenträgertypen ^2^ 3+| Ausgewogene persistente Festplatten ^3^, Performance (SSD) persistente Festplatten ^3^ und Standard (HDD) persistente Festplatten. 
|===
Anmerkungen:

. ^1^ Die Maschinen der n1-Serie stehen auf der NetApp Console bei der Bereitstellung neuer Instanzen von Cloud Volumes ONTAP in Google Cloud nicht mehr zur Auswahl. Die Maschinen der n1-Serie werden nur noch in älteren, bestehenden Systemen beibehalten und unterstützt. Neue Bereitstellungen von Cloud Volumes ONTAP werden in Google Cloud nur ab der Version 9.8 unterstützt. Wir empfehlen, auf die Maschinen der n2-Serie umzusteigen, die mit Cloud Volumes ONTAP 9.8 und höher kompatibel sind. Die Maschinen der n1-Serie stehen jedoch weiterhin für neue Bereitstellungen über die API zur Verfügung.
+
Der Maschinentyp custom-4-16384 wird von neuen Cloud Volumes ONTAP Systemen nicht mehr unterstützt. Wenn Sie bereits ein System mit diesem Maschinentyp betreiben, können Sie es weiterhin verwenden, aber wir empfehlen, auf den Maschinentyp n2-standard-4 umzusteigen.

. ^2^ Festplattenbeschränkungen können verhindern, dass Sie die maximale Systemkapazität allein durch die Verwendung von Festplatten erreichen. Sie können die Kapazitätsgrenze erreichen, indem Sie  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Tiering inaktiver Daten in den Objektspeicher"^].
+
link:reference-limits-gcp.html["Erfahren Sie mehr über die Festplattenbeschränkungen in Google Cloud"].

. ^3^ Eine verbesserte Schreibleistung wird bei Verwendung von Balanced persistent disks und Performance (SSD) persistent disks aktiviert.
+
Ab Cloud Volumes ONTAP 9.13.0 sind _Flash Cache_, hohe Schreibgeschwindigkeit und eine höhere maximale Übertragungseinheit (MTU) von 8,896 Byte für die folgenden HA-Paar-Bereitstellungsinstanzen verfügbar:

+
** n2-standard-16
** n2-standard-32
** n2-standard-48
** n2-standard-64
+
Sie können _Flash Cache_ und eine hohe Schreibgeschwindigkeit aktivieren, wenn Sie einen geeigneten Instanztyp bereitstellen. Um die höhere maximale Übertragungseinheit von 8,896 Byte zu aktivieren, müssen Sie für die Bereitstellung VPC-1, VPC-2 oder VPC-3 auswählen. Die höhere MTU ermöglicht einen höheren Netzwerkdurchsatz. Weitere Informationen zum Starten einer dieser Bereitstellungen finden Sie unter  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Starten eines HA-Paares in Google Cloud"].

+

NOTE: _Flash cache_, hoher Schreibmodus und eine MTU von 8.896 sind funktionsabhängig und können innerhalb einer konfigurierten Instanz nicht einzeln deaktiviert werden.



. ^4^ Ab dem 11. August 2025 ist die Cloud Volumes ONTAP Optimized-Lizenz veraltet und kann im Google Cloud Marketplace für Pay-as-you-go (PAYGO)-Abonnements nicht mehr erworben oder verlängert werden. Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Was ist neu in Cloud Volumes ONTAP"^].


--
.Knotenbasierte Lizenzen
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO Standard | PAYGO Premium | Knotenbasiertes BYOL 


| Maximale Systemkapazität (Festplatten + Objektspeicher) | 2 TB ^2^ | 10 TiB | 368 TiB | 368 TiB pro Lizenz 


| Unterstützte Maschinentypen ^3^  a| 
* n2-standard-4

 a| 
* n1-standard-8 ^3^
* n2-standard-8

 a| 
* n1-standard-32 ^3^
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n1-standard-8 ^3^
* n1-standard-32 ^3^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| Unterstützte Datenträgertypen 4+| Ausgewogene persistente Festplatten ^4^, Performance (SSD) persistente Festplatten ^4^ und Standard (HDD) persistente Festplatten. 
|===
Anmerkungen:

. ^1^ Festplattenbeschränkungen können verhindern, dass Sie die maximale Systemkapazität allein durch die Verwendung von Festplatten erreichen. Sie können die Kapazitätsgrenze erreichen, indem Sie  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Tiering inaktiver Daten in den Objektspeicher"^].
+
link:reference-limits-gcp.html["Erfahren Sie mehr über die Festplattenbeschränkungen in Google Cloud"].

. ^2^ Das Data Tiering zu Google Cloud Storage wird bei PAYGO Explore nicht unterstützt.
. ^3^ Die Maschinen der n1-Serie stehen bei der Bereitstellung neuer Instanzen von Cloud Volumes ONTAP in Google Cloud nicht mehr in der Konsole zur Auswahl. Die Maschinen der n1-Serie werden nur noch in älteren, bestehenden Systemen beibehalten und unterstützt. Neue Bereitstellungen von Cloud Volumes ONTAP werden in Google Cloud nur ab der Version 9.8 unterstützt. Wir empfehlen, auf die Maschinen der n2-Serie umzusteigen, die mit Cloud Volumes ONTAP 9.8 und höher kompatibel sind. Die Maschinen der n1-Serie stehen jedoch weiterhin für neue Bereitstellungen über die API zur Verfügung.
+
Der Maschinentyp custom-4-16384 wird von neuen Cloud Volumes ONTAP Systemen nicht mehr unterstützt. Wenn Sie bereits ein System mit diesem Maschinentyp betreiben, können Sie es weiterhin verwenden, aber wir empfehlen, auf den Maschinentyp n2-standard-4 umzusteigen.

. ^4^ Verbesserte Schreibleistung wird aktiviert, wenn Balanced persistent disks und Performance (SSD) persistent disks verwendet werden.


Die Konsole zeigt einen zusätzlichen unterstützten Maschinentyp für Standard und BYOL an: n1-highmem-4. Dieser Maschinentyp ist jedoch nicht für Produktionsumgebungen vorgesehen. Wir haben ihn ausschließlich für eine spezielle Laborumgebung bereitgestellt.

Ab Cloud Volumes ONTAP Softwareversion 9.13.0 sind _Flash Cache_, hohe Schreibgeschwindigkeit und eine höhere maximale Übertragungseinheit (MTU) von 8.896 Byte für die folgenden HA-Paar-Bereitstellungsinstanzen verfügbar:

* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64


Sie können _Flash Cache_ und eine hohe Schreibgeschwindigkeit aktivieren, wenn Sie einen geeigneten Instanztyp bereitstellen. Um die höhere maximale Übertragungseinheit von 8,896 Byte zu aktivieren, müssen Sie für die Bereitstellung VPC-1, VPC-2 oder VPC-3 auswählen. Die höhere MTU ermöglicht einen höheren Netzwerkdurchsatz. Weitere Informationen zum Starten einer dieser Bereitstellungen finden Sie unter  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Starten eines HA-Paares in Google Cloud"].


NOTE: _Flash cache_, hoher Schreibmodus und eine MTU von 8.896 sind funktionsabhängig und können innerhalb einer konfigurierten Instanz nicht einzeln deaktiviert werden.

--
====
Weitere Informationen zu spezifischen Maschinentypen finden Sie in der Google Cloud Dokumentation:

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["Allzweck-Maschinentypen der n1-Serie"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["Allgemeine Maschinentypen der N2-Serie"^]




== Unterstützte Festplattengrößen

In Google Cloud kann ein Aggregat bis zu 6 Festplatten desselben Typs und derselben Größe enthalten. Die folgenden Festplattengrößen werden unterstützt:

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== Unterstützte Regionen

Informationen zur Unterstützung von Google Cloud-Regionen finden Sie unter https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes Globale Regionen"^].
