---
sidebar: sidebar 
permalink: reference-configs-aws.html 
keywords: ec2, instance, type, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, sizes, disks, networking, bandwidth, professional package 
summary: Mehrere Cloud Volumes ONTAP-Konfigurationen werden in AWS unterstützt. 
---
= Unterstützte Konfigurationen für Cloud Volumes ONTAP in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mehrere Cloud Volumes ONTAP-Konfigurationen werden in AWS unterstützt.



== Unterstützte Anzahl von Knoten

Cloud Volumes ONTAP ist in AWS als Einzelknotensystem und als Hochverfügbarkeits-Knotenpaar (HA) für Fehlertoleranz und unterbrechungsfreie Vorgänge verfügbar.

Die Aufrüstung eines Einzelknotensystems auf ein HA-Paar wird nicht unterstützt. Wenn Sie zwischen einem Einzelknotensystem und einem HA-Paar wechseln möchten, müssen Sie ein neues System bereitstellen und Daten vom bestehenden System auf das neue System replizieren.



== Unterstützter Speicher

Cloud Volumes ONTAP unterstützt verschiedene Typen von EBS-Datenträgern und S3-Objektspeicher für das Data Tiering. Die maximale Speicherkapazität wird durch die gewählte Lizenz bestimmt.



=== Speicherunterstützung nach Lizenz

Jede Lizenz unterstützt eine unterschiedliche maximale Systemkapazität. Die maximale Systemkapazität umfasst den Festplattenspeicher sowie den für Data Tiering verwendeten Objektspeicher. NetApp unterstützt eine Überschreitung dieses Limits nicht.

[role="tabbed-block"]
====
.Kapazitätsbasierte Lizenzen
--
[cols="h,d,d"]
|===
|  | Freemium | Kapazitätsbasierte Lizenz 


 a| 
*Maximale Systemkapazität* (Festplatten + Objektspeicher) ^1^
| 500 GiB | Flexibel ^2^ 


 a| 
*Unterstützte Datenträgertypen*
 a| 
* General Purpose SSD (gp3 und gp2) ^3^,^5^
* Bereitgestellte IOPS SSD (io1) ^3^
* Durchsatzoptimierte HDD (st1) ^4^




 a| 
*Kalte Daten-Tiering zu S3*
 a| 
Unterstützt

|===
Anmerkungen:

. Bei einem HA-Paar gilt die Kapazitätsgrenze für das gesamte HA-Paar. Sie gilt nicht pro Knoten. Wenn Sie beispielsweise die Premium-Lizenz verwenden, können Sie bis zu 368 TiB Kapazität zwischen beiden Knoten haben.
. Bei manchen Konfigurationen verhindern Festplattenbeschränkungen, dass Sie das Kapazitätslimit allein durch die Verwendung von Festplatten erreichen. In diesen Fällen können Sie das Kapazitätslimit durch  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Tiering inaktiver Daten in den Objektspeicher"^] erreichen. Informationen zu Festplattenbeschränkungen finden Sie unter link:reference-limits-aws.html["Speichergrenzen"].
+
Mit kapazitätsbasierter Lizenzierung unterstützt jedes Cloud Volumes ONTAP-System das Tiering zu Objektspeicher. Die gesamte getierete Kapazität kann bis zum Bucket-Limit des Cloud-Anbieters skaliert werden. Obwohl die Lizenz keine Kapazitätsbeschränkungen vorsieht, sollten Sie die  https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool Best Practices"^] befolgen, um optimale Leistung, Zuverlässigkeit und Kosteneffizienz bei der Konfiguration und Verwaltung des Tierings zu gewährleisten.

. Eine verbesserte Schreibleistung wird bei Verwendung von SSDs mit allen Cloud Volumes ONTAP Konfigurationen aktiviert.
. Das Tiering von Daten auf Objektspeicher wird bei Verwendung von Throughput Optimized HDDs (st1) nicht empfohlen.
. Cloud Volumes ONTAP Konfigurationen in AWS Local Zones unterstützen nur den General Purpose SSD (gp2) Festplattentyp. Keine anderen Festplattentypen werden in Cloud Volumes ONTAP in AWS Local Zones unterstützt.


--
.Knotenbasierte Lizenzen
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO Standard | PAYGO Premium | Knotenbasiertes BYOL 


| Maximale Systemkapazität (Festplatten + Objektspeicher) | 2 TiB | 10 TiB | 368 TiB ^2^ | 368 TiB pro Lizenz ^2^ 


| Unterstützte Datenträgertypen  a| 
* General Purpose SSD (gp3 und gp2) ^3^,^5^
* Bereitgestellte IOPS SSD (io1) ^3^
* Durchsatzoptimierte HDD (st1) ^4^




| Kaltdaten-Tiering zu S3 | Nicht unterstützt 3+| Unterstützt 
|===
Anmerkungen:

. Bei einem HA-Paar gilt die Kapazitätsgrenze für das gesamte HA-Paar. Sie gilt nicht pro Knoten. Wenn Sie beispielsweise die Premium-Lizenz verwenden, können Sie bis zu 368 TiB Kapazität zwischen beiden Knoten haben.
. Bei manchen Konfigurationen verhindern Festplattenbeschränkungen, dass Sie das Kapazitätslimit allein durch die Verwendung von Festplatten erreichen. In diesen Fällen können Sie das Kapazitätslimit durch  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Tiering inaktiver Daten in den Objektspeicher"^] erreichen. Informationen zu Festplattenbeschränkungen finden Sie unter link:reference-limits-aws.html["Speichergrenzen"].
. Eine verbesserte Schreibleistung wird bei Verwendung von SSDs mit allen Cloud Volumes ONTAP Konfigurationen aktiviert, außer bei PAYGO Explore.
. Das Tiering von Daten auf Objektspeicher wird bei Verwendung von Throughput Optimized HDDs (st1) nicht empfohlen.
. Cloud Volumes ONTAP Konfigurationen in AWS Local Zones unterstützen nur den General Purpose SSD (gp2) Festplattentyp.


--
====


=== Unterstützte Festplattengrößen

In AWS kann ein Aggregat bis zu 6 gleich große Festplatten enthalten. Wenn Sie jedoch eine Konfiguration haben, die die Amazon EBS Elastic Volumes-Funktion unterstützt, kann ein Aggregat bis zu 8 Festplatten enthalten. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Erfahren Sie mehr über die Unterstützung für Elastic Volumes"^]

[cols="3*"]
|===
| Allzweck-SSDs (gp3 und gp2) | Bereitgestellte IOPS-SSDs (io1) | Durchsatzoptimierte HDDs (st1) 


 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB


|===


== Unterstützte EC2 compute

Jede Cloud Volumes ONTAP-Lizenz unterstützt unterschiedliche EC2-Instanztypen. Zur besseren Übersicht zeigt die folgende Tabelle die vCPU, den RAM und die Bandbreite für jeden unterstützten Instanztyp. https://aws.amazon.com/ec2/instance-types/["Sie sollten sich für die neuesten und vollständigen Details zu EC2-Instanztypen an AWS wenden"^]

Cloud Volumes ONTAP kann entweder auf einer Reserved- oder On-demand-EC2-Instanz ausgeführt werden. Lösungen, die andere Instanztypen verwenden, werden nicht unterstützt.

Die in der folgenden Tabelle aufgeführten Bandbreiten entsprechen den dokumentierten AWS-Grenzwerten für jeden Instanztyp. Diese Grenzwerte stimmen nicht vollständig mit dem überein, was Cloud Volumes ONTAP bereitstellen kann. Für die erwartete Leistung siehe  https://www.netapp.com/pdf.html?item=/media/9088-tr4383pdf.pdf["NetApp Technical Report 4383: Leistungscharakterisierung von Cloud Volumes ONTAP in Amazon Web Services mit Anwendungsworkloads"^].

[cols="8*"]
|===
| Lizenz | Unterstützte Instanz | vCPU | RAM | Flash Cache ^1^ | Bandbreite (Gbit/s) | EBS-Bandbreite (Mbps) | Hohe Schreibgeschwindigkeit ^2^ 


| *Explore oder eine andere Lizenz* | m5.xlarge ^6^ | 4 | 16 | Nicht unterstützt | Bis zu 10 | Bis zu 4,750 | Unterstützt (nur Einzelknoten) 


.3+| *Standard oder eine andere Lizenz* | r5.xlarge ^6^ | 4 | 32 | Nicht unterstützt | Bis zu 10 | Bis zu 4,750 | Unterstützt (nur Einzelknoten) 


| m5a.2xlarge | 8 | 32 | Nicht unterstützt | Bis zu 10 | Bis zu 2,880 | Unterstützt 


| m5.2xlarge ^6^ | 8 | 32 | Nicht unterstützt | Bis zu 10 | Bis zu 4,750 | Unterstützt 


.22+| *Premium oder eine andere Lizenz* | m5n.2xlarge | 8 | 32 | Nicht unterstützt | Bis zu 25 | Bis zu 4,750 | Unterstützt 


| r5.2xlarge ^6^ | 8 | 64 | Nicht unterstützt | Bis zu 10 | Bis zu 4,750 | Unterstützt 


| r5d.2xlarge | 8 | 64 | Unterstützt | Bis zu 10 | Bis zu 4,750 | Unterstützt 


| c5d.4xlarge ^6^ | 16 | 32 | Unterstützt | Bis zu 10 | 4.570 | Unterstützt 


| m5.4xlarge ^6^ | 16 | 64 | Nicht unterstützt | Bis zu 10 | 4.750 | Unterstützt 


| m5dn.4xlarge | 16 | 64 | Unterstützt | Bis zu 25 | 4.750 | Unterstützt 


| m5d.8xlarge | 32 | 128 | Unterstützt | 10 | 6.800 | Unterstützt 


| r5.8xlarge | 32 | 256 | Nicht unterstützt | 10 | 6.800 | Unterstützt 


| c5.9xlarge | 36 | 72 | Nicht unterstützt | 10 | 9.500 | Unterstützt 


| c5d.9xlarge | 36 | 72 | Unterstützt | 10 | 9.500 | Unterstützt 


| c5n.9xlarge | 36 | 96 | Nicht unterstützt | 50 | 9.500 | Unterstützt 


| c5a.12xlarge | 48 | 96 | Nicht unterstützt | 12 | 4.750 | Unterstützt 


| c5.18xlarge | 64 ^4^ | 144 | Nicht unterstützt | 25 | 19.000 | Unterstützt 


| c5d.18xlarge | 64 ^4^ | 144 | Unterstützt | 25 | 19.000 | Unterstützt 


| m5d.12xlarge | 48 | 192 | Unterstützt | 12 | 9.500 | Unterstützt 


| m5dn.12xlarge | 48 | 192 | Unterstützt | 50 | 9.500 | Unterstützt 


| c5n.18xlarge | 64 ^4^ | 192 | Nicht unterstützt | 100 | 19.000 | Unterstützt 


| m5a.16xlarge | 64 | 256 | Nicht unterstützt | 12 | 9.500 | Unterstützt 


| m5.16xlarge | 64 | 256 | Nicht unterstützt | 20 | 13.600 | Unterstützt 


| r5.12xlarge ^3^ | 48 | 384 | Nicht unterstützt | 10 | 9.500 | Unterstützt 


| m5dn.24xlarge | 64 ^4^ | 384 | Unterstützt | 100 | 19.000 | Unterstützt 


| m6id.32xlarge | 64 ^4^ | 512 | Unterstützt | 50 | 40.000 | Unterstützt 
|===
. Einige Instanztypen beinhalten lokalen NVMe-Speicher, den Cloud Volumes ONTAP als _Flash Cache_ nutzt. Flash Cache beschleunigt den Datenzugriff durch Echtzeit intelligentes Caching kürzlich gelesener Benutzerdaten und NetApp-Metadaten. Er ist effektiv für zufallsbasierte leseintensive Workloads, einschließlich Datenbanken, E-Mail und Dateidienste. Die Komprimierung muss auf allen Volumes deaktiviert sein, um die Leistungsverbesserungen von Flash Cache nutzen zu können. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Erfahren Sie mehr über Flash Cache"^]
. Cloud Volumes ONTAP unterstützt hohe Schreibgeschwindigkeit bei den meisten Instanztypen, wenn ein HA-Paar verwendet wird. Hohe Schreibgeschwindigkeit wird bei allen Instanztypen unterstützt, wenn ein Einzelknotensystem verwendet wird. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Erfahren Sie mehr über die Auswahl einer Schreibgeschwindigkeit"^]
. Der Instanztyp r5.12xlarge weist eine bekannte Einschränkung hinsichtlich der Supportfähigkeit auf. Wenn ein Knoten aufgrund eines Systemabsturzes unerwartet neu startet, werden möglicherweise keine Core-Dateien erfasst, die zur Fehlerbehebung und zur Ermittlung der Ursache des Problems benötigt werden. Der Kunde akzeptiert die Risiken und eingeschränkten Supportbedingungen und trägt die gesamte Supportverantwortung, falls dieser Fall eintritt. Diese Einschränkung betrifft neu bereitgestellte HA-Paare sowie HA-Paare, die von 9.8 aktualisiert wurden. Diese Einschränkung betrifft neu bereitgestellte Einzelknotensysteme nicht.
. Während diese EC2-Instanztypen mehr als 64 vCPUs unterstützen, unterstützt Cloud Volumes ONTAP nur bis zu 64 vCPUs.
. Wenn Sie einen EC2-Instanztyp auswählen, können Sie angeben, ob es sich um eine Shared Instance oder eine Dedicated Instance handelt.
. AWS Local Zones werden in den folgenden EC2-Instanztypfamilien mit Größen von xlarge bis 4xlarge unterstützt: M5, C5, C5d, R5 und R5d. link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/?nc=sn&loc=2["Sie sollten sich für die neuesten und vollständigen Details zu den in Local Zones unterstützten EC2-Instanztypen an AWS wenden"^].
+
Hohe Schreibgeschwindigkeit wird bei diesen Instanztypen in AWS Local Zones nicht unterstützt.





=== c4-, m4- und r4-Instanzen werden nicht mehr unterstützt

Cloud Volumes ONTAP unterstützt die EC2-Instanztypen c4, m4 und r4 in AWS nicht mehr. Wenn Ihr System auf einer c4-, m4- oder r4-Instanz läuft, wechseln Sie zu einer c5-, m5- oder r5-Instanz. Sie können kein Upgrade auf diese Version durchführen, bis Sie den Instanztyp geändert haben.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Erfahren Sie, wie Sie den EC2-Instanztyp für Cloud Volumes ONTAP ändern"^].

Weitere Informationen finden Sie unter:

* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Converting_an_AWS_Xen_CVO_instance_to_Nitro_KVM["Knowledge base (KB) article: Konvertierung einer AWS Xen CVO-Instanz zu Nitro KVM"^]
* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Unable_to_change_the_instance_type_from_r4_to_r5_with_disk_count_error["KB-Artikel: Instanztyp kann aufgrund eines Datenträgeranzahlfehlers nicht von r4 auf r5 geändert werden"^]
* link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Erfahren Sie mehr über das Ende der Verfügbarkeit und des Supports für diese Instanztypen"^]




== Unterstützte Regionen

Informationen zur Unterstützung von AWS-Regionen finden Sie unter https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes Globale Regionen"^].
